/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package atm_simulator.graphics;

import atm_simulator.CreateReceipt;
import atm_simulator.Log;
import atm_simulator.Withdraw;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author kanel
 */
public class WithdrawScreen extends javax.swing.JFrame {

    /**
     * Creates new form WithdrawScreen
     * @throws java.io.IOException
     */
    public WithdrawScreen() throws IOException {
        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        withdrawMsg = new javax.swing.JLabel();
        withdrawField = new javax.swing.JTextField();
        withdrawButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        withdrawMsg.setText("Enter the amount You want to withdraw");

        withdrawField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawFieldActionPerformed(evt);
            }
        });

        withdrawButton.setText("Withdraw");
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel3.setText("KK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(withdrawButton)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton))
                            .addComponent(withdrawMsg)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(withdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(79, 79, 79)
                .addComponent(withdrawMsg)
                .addGap(27, 27, 27)
                .addComponent(withdrawField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawButton)
                    .addComponent(cancelButton))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
//        new ExitMessage().ExitMessage();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        String withdrawAmount;
        int dialogButton = 0;
        withdrawAmount = withdrawField.getText();
        if(withdrawField.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Please enter the number first.");
        }
        else{
            Withdraw take = new Withdraw();
            take.setAmount(Integer.parseInt(withdrawAmount));
            if ( take.sufficientBalance())
            { 
                try {
                    Log.addLog(take);
                } catch (IOException ex) {
                    Logger.getLogger(WithdrawScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialogButton = JOptionPane.showConfirmDialog (null, "Do you want to print the receipt?","WARNING", dialogButton);
                if (dialogButton == JOptionPane.YES_OPTION) {
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null,"Please Collect your money.");
                    CreateReceipt create =  new CreateReceipt();
                    create.createReceipt(take);
                } else {
                    JOptionPane.showMessageDialog(null,"Please Collect your money.");
                    this.setVisible(false);
                    
                }
            }
        }        
    }//GEN-LAST:event_withdrawButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JTextField withdrawField;
    private javax.swing.JLabel withdrawMsg;
    // End of variables declaration//GEN-END:variables

}
